Add verbose glob error message
shakacode/sass-resources-loader pull request #134
Opened 2020-12-30 16:44 UTC by Tomburgs

Add verbose error message when any of the specified resource globs don't return any files.

Fixes: #38.

2021-01-23 12:20 UTC, Tomburgs commented
@justin808 any updates on this?

2021-01-25 01:11 UTC, justin808 requested changes
Hi @Tomburgs. Review finished!

2021-01-25 01:11 UTC, justin808 commented on src/utils/parseResources.js
>  export default locations => {
Hi @Tomburgs how do you feel about this refactoring for clarity?

This is called with:

```js
  const resourcesLocations = parseResources(resourcesFromConfig);
```

That's OK. It's either an array or list of patterns


and then that var becomes `locations` currently

and this function `getGlobPaths` takes singular `path`

Maybe we could change the function to take `pattern`

```js
const getGlobPaths = (pattern) => {
```

this file changes to take `patterns` for the argument
```js
export default patterns => {
```

And change this file and the calling reference to it to 
`expandResourceGlobs`

https://github.com/shakacode/sass-resources-loader/blob/ea22038a92/src/loader.js#L34

```js
  const resourcesLocations = expandResourceGlobs(resourcesFromConfig);
```

2021-01-25 01:11 UTC, justin808 commented on test/index.test.js
> +                  resources: [resource],
could we add the same test for the non-array case?

2021-01-26 16:54 UTC, Tomburgs commented on yarn.lock
> -eslint-plugin-eslint-plugin@^2.1.0:
It's interesting why this dependency was here in the first place.
It got added in as standalone dependency in the lockfile with #125, but before that it was added in as a dependency for `eslint-plugin-react` with #117, although as far as I can tell it was always a dev dependency for `eslint-plugin-react`, so how it got in here in the first place is beyond me.

2021-01-27 09:14 UTC, merged

2021-01-27 09:15 UTC, justin808 commented
LGTM! Thank you @Tomburgs! Great job!