Update dependencies
shakacode/sass-resources-loader pull request #157
Opened 2022-10-03 17:36 UTC by LewWadoo

This time it doesn't touch `eslint` dependency despite one of the commit messages.
- Upgrade eslint-config-airbnb
- Upgrade eslint-plugin-import, raw-loader, webpack-merge
- Upgrade glob
- Upgrade async
- Upgrade @babel/cli, @babel/core, @babel/preset-env
- Install eslint-plugin-react-hooks
- Update caniuse-lite
- Install eslint-plugin-react
- Install eslint-plugin-jsx-a11y

2022-10-04 07:37 UTC, justin808 commented
@LewWadoo 
1. List how you tested the updates.
2. Is any new release justified?

2022-10-04 07:40 UTC, justin808 requested changes
and this needs updating

2022-10-04 07:40 UTC, justin808 commented on package.json
> +    "eslint-plugin-react-hooks": "^4.6.0",
devDependencies

2022-10-04 22:19 UTC, LewWadoo commented on package.json
> +    "eslint-plugin-react-hooks": "^4.6.0",
Done

2022-10-04 22:50 UTC, LewWadoo commented
> @LewWadoo
> 
>     1. List how you tested the updates.
I relied on `yarn run test` e.g., `jest` tests. I used only this one option, so nothing to list.

>     2. Is any new release justified?
`webpack` should not be upgraded to a major release, because our documentation states that it supports **Webpack 4**. It's easier to justify minor and hotfix releases, but all my major upgrades were not justified. I just wanted to see how far I can go without breaking the tests.

2022-10-05 02:01 UTC, justin808 commented
Did CI run? I'm surprised that the code didn't need updates with the eslint changes.

2022-10-06 06:15 UTC, Judahmeek requested changes
LGTM, but would be best to wait on this until after https://github.com/shakacode/sass-resources-loader/pull/160 is merged.

2022-10-12 23:21 UTC, justin808 commented
@Judahmeek @LewWadoo what's needed to get CI to run on this branch? #160 is merged.

2022-10-12 23:21 UTC, justin808 commented
And do we need a new release?

2022-10-13 09:22 UTC, LewWadoo commented
> And do we need a new release?

I think we do. So we don't need to merge it blindly.

2022-10-14 16:11 UTC, closed without merging

2022-10-14 17:19 UTC, Judahmeek commented
@LewWadoo why not just rebase & force push to this branch instead of creating a new PR?